### ISSUE TITLE
v2.5.0 has a failing build

### ISSUE THREAD

**Issue by NilsMoller** [Nikaple/nest-typed-config#237] opened 2023-02-09 10:22 UTC
## I'm submitting a...

<pre><code>
[x] Regression 
[ ] Bug report
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request
</code></pre>

## Current behavior

Installing v2.4.7 does include the `dist`.
Installing v2.5.0 does not include the `dist`.

## Expected behavior

The `dist` folder to be included in the package, so the `index.ts` can export everything from it.

## Minimal reproduction of the problem with instructions

1. Run `npm init`
2. Run `npm install nest-typed-config`
3. See that the `dist` folder is not present.

## What is the motivation / use case for changing the behavior?

The package is currently unusable.

## Environment

<pre><code>
Nest version: N/A
 
For Tooling issues:
- Node version: 16.16.0 
- Platform: Windows

Others:

</code></pre>
This happens using both `yarn` and `npm`.

**Comment by Nikaple** [comment] 2023-02-10 07:59
Sorry for inconvenience! The problem was fixed in 2.5.1, and may be caused by some change with ci or deps, will dig into it later.

**Closed by Nikaple** 2023-02-10 07:59 UTC
